#define CONFIG_ARCH_X86
#define CONFIG_ARCH "x86"
#define CONFIG_SRCARCH "x86"
#define CONFIG_PLATFORM_PC
#define CONFIG_PLATFORM "pc"

#define CONFIG_DEBUG 1
#define CONFIG_KBOOT_UI 1

#define CONFIG_KBOOT_FS_EXT2 1
#define CONFIG_KBOOT_FS_ISO9660 1

#define CONFIG_KBOOT_PARTITION_MAP_MSDOS 1
#define CONFIG_KBOOT_HAVE_UI 1
#define CONFIG_KBOOT_HAVE_DISK 1
#define CONFIG_KBOOT_HAVE_VIDEO 1
