#define CONFIG_ARCH_ARM
#define CONFIG_ARCH "ARM"
#define CONFIG_SRCARCH "arm"
#define CONFIG_PLATFORM_OMAP3
#define CONFIG_PLATFORM "omap3"

#define CONFIG_DEBUG 1
#define CONFIG_KBOOT_UI 1

#define CONFIG_KBOOT_FS_EXT2 1
#define CONFIG_KBOOT_FS_ISO9660 1

#define CONFIG_KBOOT_PARTITION_MAP_MSDOS 1
#define CONFIG_KBOOT_HAVE_UI 1
#define CONFIG_KBOOT_HAVE_DISK 1
#define CONFIG_KBOOT_HAVE_VIDEO 1
